---
- name: install iptables-persistent
  ansible.builtin.package:
    name: iptables-persistent
    state: present
  when: ansible_os_family == "Debian"

- name: include iptables rules per chain
  ansible.builtin.include_tasks: rules.yml
  when: iptables_persistent_ipv4[__chain] is defined
  loop: ['INPUT', 'OUTPUT', 'FORWARD', 'PREROUTING', 'POSTROUTING']
  loop_control:
    loop_var: __chain
  vars:
    iptables_persistent_ip_version: 'ipv4'

- name: include ip6tables rules per chain
  ansible.builtin.include_tasks: rules.yml
  when: iptables_persistent_ipv6[__chain] is defined
  loop: ['INPUT', 'OUTPUT', 'FORWARD', 'PREROUTING', 'POSTROUTING']
  loop_control:
    loop_var: __chain
  vars:
    iptables_persistent_ip_version: 'ipv6'
