---
- name: save iptables v4 rules
  ansible.builtin.shell: iptables-save > /etc/iptables/rules.v4
  listen: persist_iptables

- name: save iptables v6 rules
  ansible.builtin.shell: ip6tables-save > /etc/iptables/rules.v6
  listen: persist_iptables
